-- SELECT * FROM RECORDS_MEMBERS;
-- SELECT * FROM TTX_TMI_STRUCTURE0;
-- SELECT * FROM TMI_ROLES;
-- SELECT * FROM TMI_MANUALS;
-- SELECT * FROM TMI_PROJECTS;
-- SELECT * FROM RECORDS_MEMBER_UNAVAILABILITY ;
-- SELECT * FROM TTX_RECORDS_MEMBER_UNAVAILABILITY0;
/*
SET @currentclubs = 'Corporate Toastmasters';
SET @currentmember = 'Yes';
SET @MeetingDate = '2017-08-30';
SET @Role1 = 'Speaker';
SET @Role2 = 'Toastmaster';
SET @Role3 = 'Speech Evaluator';
SET @Role4 = 'General Evaluator';
SET @Role5 = 'Table Topics Master';
SET @Role6 = 'Grammarian';
SET @Role7 = 'Ah-Counter';
SET @Role8 = 'Timer';
SET @Role9 = 'Table Topics Speaker';
SET @Limit1 = '3';
SET @Limit2 = '2';
SET @Limit3 = '5';
SET @Limit4 = '1';
SET @Limit5 = '1';
SET @Limit6 = '1';
SET @Limit7 = '1';
SET @Limit8 = '1';
SET @Limit9 = '6';
*/


-- ========================  SET UP ========================

-- Set key variables.
SET @currentclubs = 'Corporate Toastmasters';
SET @Club = 'Corporate Toastmasters';
SET @ClubsID = '2';
SET @currentmember = 'Yes';
SET @MeetingDate = '2017-08-30';

-- Create selection forecast table to hold selections.
DROP TABLE IF EXISTS TTX_FORECAST_SELECTIONS0;
CREATE TABLE TTX_FORECAST_SELECTIONS0 (id SERIAL , MembersID bigint(40) unsigned , NameFull VARCHAR(255) , RolesID bigint(40) unsigned , Role VARCHAR(255) , clubsID bigint(40) unsigned , meetingdate DATE);
SELECT * FROM TTX_FORECAST_SELECTIONS0;

-- ========================================================

SET @Role1 = 'Speaker';
SET @RolesID = '1';

-- Create a member/role counter from the Forecast Table
DROP TEMPORARY TABLE IF EXISTS TTX_TTX_FORECAST_SELECTION_COUNT0;
CREATE TEMPORARY TABLE TTX_TTX_FORECAST_SELECTION_COUNT0 AS
	SELECT
        MembersID ,
        NameFull ,
        COUNT(*)*100000000 AS RankAdder
    FROM TTX_FORECAST_SELECTIONS0
    WHERE
        (ClubsID = @ClubsID)
        AND (meetingdate = @MeetingDate)
    GROUP BY NameFull;
SELECT * FROM TTX_TTX_FORECAST_SELECTION_COUNT0;

-- Lists members who are UNAVAILABILE for this meeting for this role.
DROP TEMPORARY TABLE IF EXISTS TTX_RECORDS_MEMBER_UNAVAILABILITY1;
CREATE TEMPORARY TABLE TTX_RECORDS_MEMBER_UNAVAILABILITY1 AS
	SELECT * FROM TTX_RECORDS_MEMBER_UNAVAILABILITY0
	WHERE
		StartDate <= @MeetingDate
		AND  EndDate >= @MeetingDate
		AND (RolesID = '41' OR Role = @Role1);
SELECT * FROM TTX_RECORDS_MEMBER_UNAVAILABILITY1;

-- Lists members who are AVAILABILE for this meeting for this role.
DROP TEMPORARY TABLE IF EXISTS TTX_RECORDS_MEMBER_AVAILABLE1;
CREATE TEMPORARY TABLE TTX_RECORDS_MEMBER_AVAILABLE1 AS
	SELECT
		MembersID ,
        NameFull
	FROM TTX_ALLMEMBERS0
	WHERE
		currentclubs = @currentclubs
		AND currentmember = @currentmember
		AND (NameFull NOT IN (SELECT NameFull FROM TTX_RECORDS_MEMBER_UNAVAILABILITY1));
SELECT * FROM TTX_RECORDS_MEMBER_AVAILABLE1;

-- Lists ALL members for this role, ranked by date.
DROP TEMPORARY TABLE IF EXISTS TTX_MOSTRECENTROLE_ALLRANK0;
CREATE TEMPORARY TABLE TTX_MOSTRECENTROLE_ALLRANK0 AS
	SELECT
		TTX_MOSTRECENTROLE0.MembersID AS MembersID ,
        TTX_MOSTRECENTROLE0.NameFull AS NameFull ,
        TTX_MOSTRECENTROLE0.Club AS Club ,
		TTX_MOSTRECENTROLE0.Date1 AS Date1 ,
        IFNULL(TTX_TTX_FORECAST_SELECTION_COUNT0.RankAdder,'1') AS RankAdder ,
        TTX_MOSTRECENTROLE0.Date1 + IFNULL(TTX_TTX_FORECAST_SELECTION_COUNT0.RankAdder,'1') AS DateToRank
	FROM TTX_MOSTRECENTROLE0
    LEFT JOIN TTX_TTX_FORECAST_SELECTION_COUNT0 ON TTX_TTX_FORECAST_SELECTION_COUNT0.MembersID = TTX_MOSTRECENTROLE0.MembersID
	WHERE
		Role = @Role1
		AND Club = @Club
    ORDER BY DateToRank;
SELECT * FROM TTX_MOSTRECENTROLE_ALLRANK0;

-- Lists members who are AVAILABILE for this meeting for this role, ranked by date.
DROP TEMPORARY TABLE IF EXISTS TTX_MOSTRECENTROLE_AVAILABLERANK0;
CREATE TEMPORARY TABLE TTX_MOSTRECENTROLE_AVAILABLERANK0 AS
	SELECT
		TTX_RECORDS_MEMBER_AVAILABLE1.MembersID AS MembersID ,
        TTX_RECORDS_MEMBER_AVAILABLE1.NameFull AS NameFull ,
        TTX_MOSTRECENTROLE_ALLRANK0.Date1 AS Date1 ,
        TTX_MOSTRECENTROLE_ALLRANK0.RankAdder AS RankAdder ,
        TTX_MOSTRECENTROLE_ALLRANK0.Date1 + TTX_MOSTRECENTROLE_ALLRANK0.RankAdder AS DateToRank
	FROM TTX_RECORDS_MEMBER_AVAILABLE1
	LEFT JOIN TTX_MOSTRECENTROLE_ALLRANK0 ON TTX_RECORDS_MEMBER_AVAILABLE1.NameFull = TTX_MOSTRECENTROLE_ALLRANK0.NameFull
	ORDER BY DateToRank , NameFull;
SELECT * FROM TTX_MOSTRECENTROLE_AVAILABLERANK0;

DROP TEMPORARY TABLE IF EXISTS TTX_ROLESELECTION0;
CREATE TEMPORARY TABLE TTX_ROLESELECTION0 AS
	SELECT
		MembersID ,
    NameFull
	FROM TTX_MOSTRECENTROLE_AVAILABLERANK0
    ORDER BY DateToRank
    LIMIT 3;
SELECT * FROM TTX_ROLESELECTION0;

INSERT INTO TTX_FORECAST_SELECTIONS0 (MembersID , NameFull , RolesID , Role, clubsID , meetingdate)
	SELECT
		MembersID AS MembersID,
		NameFull as NameFull,
		@RolesID AS RolesID,
		@Role1 AS Role,
		@ClubsID AS ClubsID,
		@MeetingDate AS MeetingDate
	FROM TTX_ROLESELECTION0;

SELECT * FROM TTX_FORECAST_SELECTIONS0;
