
-- Show all unavailable members
SET @MeetingDate1 = '2017-11-08';
SET @ClubsID = '2';

SELECT
	RECORDS_MEMBER_UNAVAILABILITY.id AS TableID ,
	RECORDS_MEMBER_UNAVAILABILITY.membersID AS MembersID ,
	CONCAT(RECORDS_MEMBERS.NameFirst , ' ' , RECORDS_MEMBERS.NameLast) AS NameFull ,
	RECORDS_MEMBERS.ClubsID AS ClubsID ,
	RECORDS_MEMBER_UNAVAILABILITY.rolesID AS RolesID ,
	TMI_ROLES.Role AS Role ,
	RECORDS_MEMBER_UNAVAILABILITY.startdate AS StartDate ,
	RECORDS_MEMBER_UNAVAILABILITY.enddate AS EndDate ,
	RECORDS_MEMBER_UNAVAILABILITY.reason AS Reason ,
	RECORDS_MEMBER_UNAVAILABILITY.notes AS Notes
FROM RECORDS_MEMBER_UNAVAILABILITY
LEFT JOIN RECORDS_MEMBERS ON RECORDS_MEMBERS.id = RECORDS_MEMBER_UNAVAILABILITY.membersID
LEFT JOIN TMI_ROLES ON TMI_ROLES.id = RECORDS_MEMBER_UNAVAILABILITY.RolesID
WHERE StartDate <= @MeetingDate1 AND EndDate >= @MeetingDate1 AND ClubsID = @ClubsID;

-- Show all available members
SELECT
	TX_ALLMEMBERS0.MembersID ,
	TX_ALLMEMBERS0.NameFull
FROM TX_ALLMEMBERS0
WHERE
	currentmember = 'Yes'
	AND ClubsID = @ClubsID
	AND TX_ALLMEMBERS0.MembersID NOT IN
		(SELECT MembersID FROM RECORDS_MEMBER_UNAVAILABILITY
		WHERE StartDate <= @MeetingDate1 AND EndDate >= @MeetingDate1)
		ORDER BY TX_ALLMEMBERS0.NameFull;
