
-- RECORDS_PROJECTS view with detail.
SELECT
	-- RECORDS_PROJECTS.membersID AS MembersID ,
	CONCAT(RECORDS_MEMBERS.NameFirst , ' ' , RECORDS_MEMBERS.NameLast) AS NameFull ,
	-- RECORDS_MEMBERS.ClubsID AS ClubsID ,
	-- RECORDS_PROJECTS.QualificationsID AS QualificationsID,
	TMI_QUALIFICATIONS.qualification AS Qualification ,
	-- RECORDS_PROJECTS.ProjectsID ,
	TMI_PROJECTS.project AS Project ,
	-- RECORDS_PROJECTS.RolesID AS RolesID,
	TMI_ROLES.role AS Role,
	DATE_FORMAT(RECORDS_PROJECTS.MeetingDate , "%d-%b-%y") ,
	RECORDS_PROJECTS.itemstatus ,
	RECORDS_PROJECTS.Comments
FROM RECORDS_PROJECTS
	LEFT JOIN RECORDS_MEMBERS ON RECORDS_MEMBERS.id = RECORDS_PROJECTS.membersID
	LEFT JOIN TMI_QUALIFICATIONS ON TMI_QUALIFICATIONS.id = RECORDS_PROJECTS.qualificationsID
	LEFT JOIN TMI_PROJECTS ON TMI_PROJECTS.id = RECORDS_PROJECTS.projectsID
	LEFT JOIN TMI_ROLES ON TMI_ROLES.id = RECORDS_PROJECTS.rolesID
/*
WHERE
	RECORDS_PROJECTS.RolesID = '1'
	AND RECORDS_MEMBERS.ClubsID = '1'
*/
ORDER BY RECORDS_PROJECTS.MeetingDate DESC;
