


SET @Role = 'General Evaluator';

DELIMITER //
	CREATE PROCEDURE P_TEST (IN _START INTEGER , IN _LIMIT INTEGER)

		BEGIN
			PREPARE STMT FROM
				" SELECT * FROM TTX_MOSTRECENTPROJECT0 LIMIT ? ,?" ;
			SET @START = _START;
	    SET @LIMIT = _LIMIT;
	    EXECUTE STMT USING @START, @LIMIT;
	    DEALLOCATE PREPARE STMT;
		END //
DELIMITER ;

CALL P_TEST;

DROP PROCEDURE P_TEST;



DELIMITER //

  CREATE PROCEDURE `some_proc` (IN _START INTEGER , IN _LIMIT INTEGER)

  BEGIN
    PREPARE STMT FROM " SELECT * FROM products LIMIT ?,? ";
    SET @START = _START;
    SET @LIMIT = _LIMIT;
    EXECUTE STMT USING @START, @LIMIT;
    DEALLOCATE PREPARE STMT;
  END //

DELIMITER ;
