DROP VIEW IF EXISTS xshortlist;
CREATE VIEW xshortlist AS
	SELECT 
		NameFull
	FROM V_CONTESTABLE_TMIROLES_TO_MEMBERS2
	GROUP BY NAMEFULL
	LIMIT 5;
SELECT * FROM xshortlist;

DROP VIEW IF EXISTS xrolerank;
CREATE VIEW xrolerank AS
	SELECT 
		V_CONTESTABLE_TMIROLES_TO_MEMBERS2.NameFull AS NameFull,
		V_CONTESTABLE_TMIROLES_TO_MEMBERS2.Role AS Role,
		IFNULL(CAST(V_MOSTRECENTROLE1.Date1 AS unsigned),1) AS Date1Num
	FROM V_CONTESTABLE_TMIROLES_TO_MEMBERS2
	LEFT JOIN V_MOSTRECENTROLE1 ON V_MOSTRECENTROLE1.NameFull_Role = V_CONTESTABLE_TMIROLES_TO_MEMBERS2.NameFull_Role;
SELECT * FROM xrolerank;

SELECT * FROM xrolerank
WHERE NameFull NOT IN (SELECT * FROM xshortlist);

