SELECT * FROM RECORDS_PROJECTS;
SELECT * FROM V_RECORDS_PROJECTS1;
SELECT * FROM V_TMI_STRUCTURE0;

DROP VIEW IF EXISTS V_RECORDS_PROJECTS_CLEANING0;
CREATE VIEW V_RECORDS_PROJECTS_CLEANING0 AS
	SELECT
			RECORDS_PROJECTS.id AS ID ,
			RECORDS_PROJECTS.projectsID AS ProjectsID ,
            V_TMI_STRUCTURE0.Project AS TMIProject ,
			RECORDS_PROJECTS.RolesID AS PRolesID ,
			V_TMI_STRUCTURE0.RolesID AS TMIRolesID ,
			(RECORDS_PROJECTS.RolesID) / (V_TMI_STRUCTURE0.RolesID) AS Diff
	FROM RECORDS_PROJECTS
	LEFT JOIN V_TMI_STRUCTURE0 ON V_TMI_STRUCTURE0.projectsID = RECORDS_PROJECTS.projectsID;

SELECT * FROM V_RECORDS_PROJECTS_CLEANING0;
SELECT * FROM V_RECORDS_PROJECTS_CLEANING0
WHERE Diff <> '1';
